development:
  adapter: postgresql
  encoding: unicode
  database: seer_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: seer_test
  username: postgres
  password: postgres
